import Head from 'next/head';
import { Inter } from '@next/font/google';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });
const Member = () => {
  return (
    <>
      <Head>
        <title>Crewmeister coding challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main} ${inter.className}`}>
        <p>member</p>
      </div>
    </>
  );
};

export default Member;
