import Head from 'next/head';
import styles from '../../src/styles/Home.module.css';

import { useEffect, useState } from 'react';
import TableComponent from '../../components/TableComponent';

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [absenceState, setAbsenceState] = useState<any | null>([]);
  const [vacationType, setVacationType] = useState('');
  const [startDate, setStartDate] = useState('');

  const columns = [
    {
      Header: 'Member name',
      accessor: 'name',
    },
    {
      Header: 'Type of absence',
      accessor: 'type',
    },
    {
      Header: 'Period',
      accessor: 'period',
    },
    {
      Header: 'Member note',
      accessor: 'memberNote',
    },
    {
      Header: 'Status',
      accessor: 'status',
    },
    {
      Header: 'Admitter note',
      accessor: 'admitterNote',
    },
    {
      Header: 'Start date',
      accessor: 'startDate',
    },
    {
      Header: 'End date',
      accessor: 'endDate',
    },
  ];

  useEffect(() => {
    setIsLoading(true);
    fetch(`/api/absences`)
      .then((res) => res.json())
      .then((data) => {
        if (vacationType && startDate) {
          setAbsenceState(
            data.filter(
              (x: any) => x.type === vacationType && x.startDate >= startDate
            )
          );
        } else if (vacationType) {
          setAbsenceState(data.filter((x: any) => x.type === vacationType));
        } else if (startDate) {
          setAbsenceState(data.filter((x: any) => x.startDate >= startDate));
        } else {
          setAbsenceState(data);
        }
        setIsLoading(false);
      })
      .catch((error) => {
        setError(error.error);
        setIsLoading(false);
      });
  }, [vacationType, startDate]);

  return (
    <>
      <Head>
        <title>Crewmeister coding challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Absence Manager</h1>
        <div className={styles.tableHeader}>
          <div>
            <p className={styles.totalTitle}>Total number of absences</p>
            <h6 className={styles.total}>{absenceState?.length}</h6>
          </div>
          <div>
            <p className={styles.totalTitle}>Filter by absence type</p>
            <select
              name="absenceType"
              id="absenceType"
              className={styles.selectInput}
              onChange={(e) => setVacationType(e.target.value)}
            >
              <option value="">All</option>
              <option value="sickness">Sickness</option>
              <option value="vacation">Vacation</option>
            </select>
          </div>
          <div>
            <p className={styles.totalTitle}>Filter by start date</p>
            <input
              type="date"
              className={styles.selectInput}
              onChange={(e) => setStartDate(e.target.value)}
            />
          </div>
        </div>

        <TableComponent
          tableColumns={columns}
          tableData={absenceState}
          isLoading={isLoading}
          error={error}
        />
      </main>
    </>
  );
}
